= Changelog
:url-repo: https://gitlab.com/antora/antora-lunr-extension

This document provides a summary of all notable changes to this project grouped by release.
For a detailed view of what's changed, refer to the {url-repo}/commits[commit history] of this project.

== Unreleased

=== Changed

* Remove workaround for #44 now that streams can safely be written to multiple destinations starting in Antora 3.0.3
* upgrade lunr-languages from 1.9 to 1.10; changes nodejieba dependency to @node-rs/jieba (#60)

== 1.0.0-alpha.8 (2022-05-23)

=== Fixed

* Compile `search-ui.js` before releasing

== 1.0.0-alpha.7 (2022-05-23)

=== Fixed

* Create stream for vendored JS file on demand to support multiple destinations (#44)
* Automatically add `tinyseg.js` needed for Japanese support and `wordcut.js` needed for Thai support (#45)

=== Changed

* Automatically add `search-ui.js` and `search.css` files (if they don't exist) and remove dependency on supplemental UI (#15)
* Remove position metadata from the index to reduce its size (#41)

=== Added

* Allow to restrict search to current component using a checkbox (#4)
* Display each search result under the title and version of the component the result is from (#35)
* Support multi-terms highlighting and highlight term on titles (#41)
* Add Apache Solr to the "Who's using it?" section
* Run the test suite on Windows

== 1.0.0-alpha.6 (2022-03-15)

=== Fixed

* Set an identifier on section titles document (#37)
* Fix ternary condition using parenthesis

== 1.0.0-alpha.5 (2022-02-18)

=== Changed

* Use numerical identifiers in order to reduce the index size (#33)
* Disable the search bar until the index is loaded and publish an event (#34)

== 1.0.0-alpha.4 (2022-01-27)

=== Fixed

* Correctly detect custom search-scripts.hbs partial (#32)

== 1.0.0-alpha.3 (2022-01-17)

=== Fixed

* Add data directory to npm package (#31)

== 1.0.0-alpha.2 (2022-01-16)

=== Added

* Set `SITE_SEARCH_LANGUAGES` env var to a comma-separated list of languages if non-en languages are specified (#17)
* Automatically manage the search-scripts.hbs partial and remove from supplemental_ui (#17)
* Allow length of snippets in search results to be configured using `snippet_length` key (#14)

=== Changed

* Only attempt to load search stylesheet if specified in `data-stylesheet` attribute on search script (#20)
* Don't parse HTML of pages that have the `noindex` AsciiDoc attribute (#19)
* Don't parse HTML of pages not in the latest version when `index_latest_only` option is set (#23)
* Build the indexable documents in serial so the parsed HTML for only one page is held in memory at a time (#22)
* Close search on click outside search interface instead of on blur (#25)

=== Fixed

* Fix require statement for PassThrough in lazy-readable.js so it retrieves it from *stream* instead of *readable-stream* (#24)
* Publish the language support scripts as lunr-languages.js and load it into the browser, if necessary (#17)

== 1.0.0-alpha.1 (2021-12-20)

=== Added

* Initial rerelease of Antora Lunr integration as an Antora extension
* Expose `generateIndex` as exported function of main script and require path `@antora/lunr-extension/generate-index` (#9)

=== Changed

* Move lib/extension.js to lib/index.js (#6)
* Move supplemental_ui/js/vendor/search.js to supplemental_ui/js/search-ui.js
* Don't vendor lunr.js script in repository; grab it from require path (#11)
* Configure package exports to both limit what files can be required and to define a require API (#6)
* Use generator context bound to register function of extension instead of function argument
* Pass logger as keyword argument named `logger` to `generateIndex` function (#10)
* Make keyword arguments on `generateIndex` function optional (#10)
* Automatically manage env var to activate elements in UI; make `DOCSEARCH_ENABLED` and `DOCSEARCH_ENGINE` env vars obsolete (#12)
* Move the responsibility of inserting the search stylesheet to the search script; drop the head-meta.hbs template from the supplemental UI (#12)
* Pass site root path using `data-site-root-path` attribute on script tag instead of `data-base-path`
* Move the responsibility of including the search scripts to the UI; move footer-scripts.hbs to search-scripts.hbs
* Only style the highlighted term in bold; style the document title in bold; adjust the font color and spacing in results
* Increase the maximum snippet length from 15 to 100
* Convert README from Markdown to AsciiDoc
* Change license from MIT to MPL-2.0

=== Fixed

* Catch invalid query and only log message at debug level if lunr-debug=1 query string parameter is set (#13)
